---
title: "surprisal-plots"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(dplyr.summarise.inform = FALSE)

# Results

library(tidyverse)
library(widyr)
library(ggthemes)
#library(devtools)
#install_github("langcog/langcog")
library(ggstance)
library(langcog)
library(ggdendro)
library(ggplot2)#
library(glue)

walk(list.files("scripts", pattern = "*.R$", full.names = TRUE), source)
```

```{r basic_plots, fig.width=14, fig.height=10, fig.cap="Plotting each predictor with AOA for all languages, within each lexical category. N_types is unexpected, maybe because it relies on matching of definitions to CHILDES words which is not precise enough."}
#aoa_predictor_data <- readRDS("./surprisals/lstm_aoa_predictor_data.rds" )

ggplot(aoa_predictor_data, aes(x = all_frequency, y = aoa)) + 
  geom_point(aes(x = all_frequency, y = aoa, col=language), alpha = .1) + 
  facet_grid(measure~lexical_category) +
  geom_smooth(method = "lm") + 
 # facet_grid(language ~ lexical_class, scales = "free_x") + 
 # langcog::theme_mikabr() + 
 # langcog::scale_color_solarized() + 
  theme(legend.position = "bottom") + 
  xlab("Frequency") + 
  #scale_x_reverse(limits = c(3.5, -5.0))+
  ylab("Age of Acquisition (months)")+
  theme(legend.position="none")+
  theme_bw()+
  ggtitle("Frequency~AOA")

 ggplot(aoa_predictor_data, aes(x = avg_surprisal, y = aoa)) + 
  geom_point(aes(x = avg_surprisal, y = aoa, col=language), alpha = .1) + 
  facet_grid(measure~lexical_category) +
  geom_smooth(method = "lm") + 
 # facet_grid(language ~ lexical_class, scales = "free_x") + 
 # langcog::theme_mikabr() + 
 # langcog::scale_color_solarized() + 
  theme(legend.position = "bottom") + 
  xlab("Average Surprisal") + 
  #scale_x_reverse(limits = c(3.5, -5.0))+
  ylab("Age of Acquisition (months)")+
  theme(legend.position="none")+
  theme_bw()+
  ggtitle("Average Surprisal~AOA")


ggplot(aoa_predictor_data, aes(x = concreteness, y = aoa)) + 
  geom_point(aes(x = concreteness, y = aoa, col=language), alpha = .1) + 
  facet_grid(measure~lexical_category) +
  geom_smooth(method = "lm") + 
 # facet_grid(language ~ lexical_class, scales = "free_x") + 
  langcog::theme_mikabr() + 
  langcog::scale_color_solarized() + 
  theme(legend.position = "bottom") + 
  xlab("Concreteness") + 
  #scale_x_reverse(limits = c(1, -3.0))+
  ylab("Age of Acquisition (months)")+
  theme(legend.position="none")+
  theme_bw()+
  ggtitle("Concreteness~AOA")


```

```{r setup2, include=FALSE}
#aoa_coefs<- readRDS("./surprisals/lstm_surprisal_aoa_coefs.rds") 
 
label_caps <- function(value) {
  if_else(toupper(value) == value, value,
          paste0(toupper(substr(value, 1, 1)),
                 tolower(substr(value, 2, nchar(value))))) %>%
    str_replace_all("_", " ")
}
target_langs <- unique(aoa_coefs$language)
num_langs <- n_distinct(aoa_coefs$language)
predictors <- unique(aoa_coefs$term)
preds_=list(predictors)
num_coefs <- length(predictors)
display_predictors <- function(predictors) {
  predictors %>%
    str_replace("num", "number") %>% str_replace("phons", "phonemes") %>%
    map_chr(label_caps) %>% str_replace("Mlu", "MLU-w")
}

```

```{r refcoefs,  fig.width=14, fig.height=7, fig.cap="To illustrate the structure of our analysis, we first describe the results for English data, as the main effect coefficients in predicting words' developmental trajectories for English comprehension and production data. Larger coefficient values indicate a greater effect of the predictor on acquisition: positive main effects indicate that words with higher values of the predictor tend to be understood/produced by more children, while negative main effects indicate that words with lower values of the predictor tend to be understood/produced by more children. Line ranges indicates 95\\% confidence intervals; filled in points indicate coefficients for which $p < 0.05$."}

#mean_term_coefs <- aoa_coefs %>%
#  filter(effect=="main") %>%
#  group_by(term) %>%
#  summarise(mean_estimate = mean(estimate),
#            n_sig = sum(signif),
#            n_pos = sum(estimate > 0),
#            n_neg = sum(estimate < 0)) %>%
#  arrange(desc(abs(mean_estimate)))

#mean_term_measure_coefs <- aoa_coefs %>%
#  filter(effect=="main") %>%
#  group_by(measure, term) %>%
#  summarise(mean_estimate = mean(estimate),
#            n_sig = sum(signif),
#            n_pos = sum(estimate > 0),
#            n_neg = sum(estimate < 0)) %>%
#  arrange(desc(abs(mean_estimate)))

#mean_term_coef <- function(t, r = 2) {
#  coef <- mean_term_coefs %>%
#    filter(term == t) %>%
#    pull(mean_estimate) %>%
#    round(r)
#  sprintf("$\\bar{\\beta} = %s$", coef)
#}
#mean_term_measure_coef <- function(meas, t) {
#  coef <- mean_term_measure_coefs %>%
#    filter(term == t, measure == meas) %>%
#    pull(mean_estimate) %>%
#    round(2)
#  sprintf("$\\bar{\\beta} = %s$", coef)
#}

#coef_order <- mean_term_coefs %>% pull(term)

ref_coefs <- aoa_coefs %>% filter(language == "English (American)")

plt_main_coefs <- ref_coefs %>%
  mutate(term = term %>% #factor(levels = rev(coef_order)) %>%
           fct_relabel(display_predictors),
         signif = if_else(signif, "significant", "non-significant") %>%
           fct_rev(),
         measure = fct_recode(measure, "comprehension" = "understands",
                              "production" = "produces")) %>%
  filter(!is.na(term)) %>%
  filter(effect=="main")

plt_main_coefs$term <- factor(plt_main_coefs$term, levels=c("All frequency", "Avg surprisal", "Concreteness", "Function words", "Predicates", "Nouns"))

ggplot(plt_main_coefs, aes(x = estimate, y = term)) +
  facet_grid(language ~ measure, scales = "free",
             labeller = as_labeller(label_caps)) +
  geom_pointrangeh(aes(colour = term, shape = signif,
                       xmin = estimate - 1.96 * std.error,
                       xmax = estimate + 1.96 * std.error)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted") +
  #scale_colour_ptol(guide = FALSE) +
  scale_shape_manual(values = c(19, 21), guide = FALSE) +
  theme_bw()+
  labs(y = "", x = "Coefficient estimate")

```


Predictors with lexical category interactions
```{r lexcatcoefs, fig.width=14, fig.height=10, fig.cap="LEXICAL CATEGORY : Estimates of effects in predicting words' developmental trajectories for each language, measure, and lexical category (main effect of predictor + main effect of lexical category + interaction between predictor and lexical category). Each point represents a predictor's effect in one language, with the bar showing the mean across languages."}
lex_cat<- c("nouns", "predicates", "function_words")

predictor_effects <- aoa_coefs %>%
  filter(effect == "main" & !(term %in% lex_cat)) %>%
  rename(predictor_effect_estimate = estimate) %>%
  select(c(language, measure, term, predictor_effect_estimate))
nouns_coefs <- predictor_effects %>% 
  mutate(lexical_category = "nouns") %>% 
  rename(estimate = predictor_effect_estimate)

lexcat_effects <- aoa_coefs %>%
  filter(effect == "main" & term %in% lex_cat ) %>%
 #  mutate(lexical_category = str_match(term, ": (.*)$")[,2]) %>%
  rename(lexcat_effect_estimate = estimate) %>%
  select(language, measure, term, lexcat_effect_estimate) %>%
  rename(lexical_category = term)


lexcat_coefs <- aoa_coefs %>%
  filter(str_detect(effect, "interaction")) %>%
  # mutate(lexical_category = str_match(effect, ": (.*)$")[,2]) %>%
  rename(interaction_estimate = estimate) %>%
  select(c(language, measure, lexical_category, term, interaction_estimate)) %>%
  # select(-effect) %>%
  left_join(predictor_effects) %>%
  left_join(lexcat_effects) %>%
  mutate(estimate = predictor_effect_estimate +
           lexcat_effect_estimate + interaction_estimate) %>%
  distinct()  %>% 
  select(-c(interaction_estimate, lexcat_effect_estimate, predictor_effect_estimate)) %>% 
  full_join(nouns_coefs)



ggplot(lexcat_coefs, aes(x = estimate, y = term, colour = language)) +
  facet_grid(measure ~ lexical_category) +
  geom_point(size = 3, alpha = 0.4) +
  stat_summaryh(geom = "crossbarh", fun.x = mean, fun.xmin = mean,
                fun.xmax = mean, fatten = 3) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted") +
  scale_colour_ptol(guide = FALSE) +
  theme_bw()+
  labs(x = "Coefficient estimate", y = "")

```

